# Index

## LIST
- Understanding list
- Creating list
- Adding element to list
- Understanding Indexing
- Changing elements inside a list
- Finding index of a known element 
- working with built in functions

# List

- Ordered
- Changeable
- Heterogeneous

List is a sequence of values:
 - Values can be of any type
 - Values in list are called **Elements** or **items**
 

- List is the most versatile datatype available in Python

## Creating new list

Creating a new list<br>
Syntax
```
variable_name = [] # this creates a empty list
```
- The values to be passed inside the list are written inside the list
- The values are seperated by comas `,`
- The vales can be of any type

### Creating an Empty list

In [ ]:
name = [] #this is a empty list
type(name)

### Creating a list using the list constructor

In [ ]:
name = list()
print(name)
type(name)

### Creating list with Elements

In [ ]:
fruits = ["apple","mango","banana","guava"]
numbers = [1,2,44,55,66,44,5]
random = ["names","numbers",1,2,3,"float",22.5.6,True,False]

## Indexing

- A list is ordered
- They have a specific order
- Each element inside the list is given a specific position
    - This is known as mapping
- Each element inside the list is given a specific position called as Index
> Index starts at 0

Which means that
- First element is given the index value - 0
- Second element is given the index value - 1 and so on ..

- As the values are indexed it is possible
    - To change a value at a specific index (as lists are mutable)
    - Add elements using index
    - Get the value of elements in a specific location

<font color=red>**Question 1**</font><br>
Tell me the index of character **#** in the following lists:
```
    A = [ 1, 2, 3, '#', 5, 6, 7 ]
    B = [ '#', '*', '&', '-', '+' ]
    C = [ 'twitter, 'instagram', 'facebook', '#' ]
    D = [ [1,'#'], [2,2], [3,3] ]
    D = [ '#twitter', 'instagram', 'facebook' ]
```

## Adding Elements to a List

#### Method 1: Direct Assigning
```
eg:-
lis = ['Anil',20,65.5,175]
```

##### Method 2: Using append() method
<b>Syntax</b>
```
name_of_list.append(value)
```
- value to be added has to be passed inside the paranthesis of the append

- The value is added as the last element of the list


#### Method 3: Using insert() method
<b>Syntax</b>
```
name_of_list.insert(index,element)
```
- insert the element into the offset position(index) of the list.
- To insert into an empty list, use **0** as index


#### Method 4: Using extend() method
<b>Syntax</b>
```
name_of_list.extend(sequence)
```
- Appends the contents of sequence into the list
- Here sequence can  be another list/tuple/set
- We will discuss this later

### Directly Assign Elements to the List

In [ ]:
# METHOD-1 Example

### append() method

In [ ]:
# METHOD-2 Example

In [ ]:
name.append("rekha")
name.append("mishal")
name.append("anjana")
name.append("athira")
name.append("ifna")
name.append("abhinav")
name.append("niharika")
name.append("aiswarya")
name.append("Muhammed Mishal")
name.append("gayathri")
print(name)

### insert() method

In [ ]:
# METHOD-3 Example
# insert to empty list

In [ ]:
#insert at the end

In [ ]:
#insert to middle

## Accessing list elements

### Using Index

*SYNTAX*
```
name_of_list[index]
```
- This gives us the element residing at that index.

#### 1-Dimensional

In [ ]:
football = ["messi","ronaldo","pele","chethri"]
a = football[2] # Get the value at index 2
print(a)

#### 2-Dimensional

In [ ]:
list_1 = [1,2,3,[4,5,6]]
print(list_1[1])

2

<font color=red>**Question 2**</font><br>
`list_1 = [1,2,3,[4,5,6]]`    
How can we print the value 5?

## Transversal through a list

### Transversal using while loop

In [ ]:
new_list = ["areej","akarsh","amrutha","shahan","arjun","akshaya","raya","adarsh"]
length = len(new_list)
print("length:",length)
a=0
while a<8:
    print(new_list[a]) 
    a+=1

In [ ]:
# While Loop
# using while loop print all the elements in a list
random = ["names","numbers",1,2,3,"float",225.6,True,False]
x=0
while x<len(random):
    print(random[x])
    x=x+1

### Traversal of list elements using for loop

**Syntax:**
```
for item in list_name:
    print(item)
```
- Here item is just an identifier you can give any name
- In each iteration of the for loop `item` carries one element of the list.
- Iteration will occur `n-times`, where `n` is the number of elements in the list.
- Iteration will take elements from the list in the order they appeared in the list. i.e from index position `0` to `-1`.

**Note:** In this case we need not to worry about the index.

In [ ]:
new_list = ["areej","akarsh","amrutha","shahan","arjun","akshaya","raya","adarsh"]
for name in new_list:
    print(name)

areej
akarsh
amrutha
shahan
arjun
akshaya
raya
adarsh

In [ ]:
#To print index along with the item
new_list = ["areej","akarsh","amrutha","shahan","arjun","akshaya","raya","adarsh"]
a=0
for name in new_list:
    a=a+1
    print(a,name)

1 areej
2 akarsh
3 amrutha
4 shahan
5 arjun
6 akshaya
7 raya
8 adarsh

In [ ]:
random = ["names","numbers",1,2,3,"float",225.6,True,False]
print(random)
print("------")
for a in random:
    print(a)

['names', 'numbers', 1, 2, 3, 'float', 225.6, True, False]
------
names
numbers
1
2
3
float
225.6
True
False

<font color=red>**Question 3**</font><br>
`new_list = [1,2,3,4,5]`

multiply each element with 10 then add to the element and update the list.
```
OUTPUT
-------
new_list = [11,22,33,44,55]
```

<font color=red>**Question 4**</font><br>
new_list = ["areej","adarsh","amrutha","shahan","arjun","akshaya","rayan","akash"]

create a new list and add "#" as the first character of the elements
```
OUTPUT
-------
new_list = ["#areej","#adarsh","#amrutha","#shahan","#arjun","#akshaya","#rayan","#akash"]
```

## Changing the values inside a list

**Note:** As lists are mutable, it is possible to change the values inside a list


- This can be achieved using indices and assignment operator


- No extra method is needed for updating a list element

**Syntax:**
```
list_name[index] = new_value
```
- Here index is the index of the element which we want to altrered.

In [ ]:
marks = [65,76,94,72,80]
# We want to change the mark 72 into 75
print("Before: ",marks)
marks[3] = 75
# marks[-2] = 75
print("After: ",marks)

Before:  [65, 76, 94, 72, 80]
After:  [65, 76, 94, 75, 80]

In [ ]:
# changing value at 2 index to anjana_k
batch_2 = ['rekha', 'mishal', 'anjana', 'athira', 'ifna', 'abhinav', 'niharika', 'aiswarya', 'Muhammed Mishal', 'gayathri']
batch_2[2] = "Anjana_K"
print(batch_2)

['rekha', 'mishal', 'Anjana_K', 'athira', 'ifna', 'abhinav', 'niharika', 'aiswarya', 'Muhammed Mishal', 'gayathri']

<font color=red>**Question 5**</font><br>
```
name = ['rekha', 'mishal', 'Anjana_K', 'athira', 'ifna', 'abhinav', 'niharika', 'aiswarya', 'Muhammed Mishal', 'gayathri']
```
- Add ": python" to all the elements 
- print the updated list :- with updated elements

In [ ]:
# Not recommended Method

name = ['rekha', 'mishal', 'Anjana_K', 'athira', 'ifna', 'abhinav', 'niharika', 'aiswarya', 'Muhammed Mishal', 'gayathri']
print(len(name))
name[0]=name[0] + ":print"
name[1]=name[1] + ":print"
name[2]=name[2] + ":print"
name[3]=name[3] + ":print"
name[4]=name[4] + ":print"
name[5]=name[5] + ":print"
name[6]=name[6] + ":print"
name[7]=name[7] + ":print"
name[8]=name[8] + ":print"
name[9]=name[9] + ":print"
print(name)

In [ ]:
# Not recommended Method

name = ['rekha', 'mishal', 'Anjana_K', 'athira', 'ifna', 'abhinav', 'niharika', 'aiswarya', 'Muhammed Mishal', 'gayathri']
n=0
while n<len(name): # head
    name[n]=name[n]+":python" #body
    n=n+1 # n += 1 #body
print(name) # out of the body :: not part of while

In [ ]:
name = ['rekha', 'mishal', 'Anjana_K', 'athira', 'ifna', 'abhinav', 'niharika', 'aiswarya', 'Muhammed Mishal', 'gayathri']
i=0
for x in name:
    name[i] = x + ":python"
    i+=1
print(name)

In [ ]:
name = ['rekha', 'mishal', 'Anjana_K', 'athira', 'ifna', 'abhinav', 'niharika', 'aiswarya', 'Muhammed Mishal', 'gayathri']
b = "python"
for a in name:
    print(a,b)
print("-----------")
print("LIST")
print(name)

## Basic List Operations

### Addition

In [ ]:
list1 = [1,2,3,4]
list2 = [-1,-2,-3,-4]
print(list1+list2)

[1, 2, 3, 4, -1, -2, -3, -4]

In [ ]:
num_1 = [1,2,3]
num_2 = [4,5,6]
Sum = num_1 + num_2
print(Sum)
print(num_1)
print(num_2)

[1, 2, 3, 4, 5, 6]
[1, 2, 3]
[4, 5, 6]

### Multiplication

In [ ]:
num_2 = [1,2,3]
num_1 = ["a","b","c"]
print(num_1*2) # num_1 + num_1
print(num_2*3) # num_2+num_2+num_2

['a', 'b', 'c', 'a', 'b', 'c']
[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [ ]:
name = ["ak","ac"]
name_2 = ["mm","nn"]
name_3 = name*2 +name_2
print(name_3,type(name_3))

['ak', 'ac', 'ak', 'ac', 'mm', 'nn'] <class 'list'>

In [ ]:
list_1=[1,2]
print(list_1*4)
print(list_1)

[1, 2, 1, 2, 1, 2, 1, 2]
[1, 2]

## List Slicing and negative indexing

**Syntax:**
```
sub_list = list_name[start_index:end_index:step]
```

In [ ]:
random = ["names","numbers",1,2,3,"float",225.6,True,False]

# names - 0
# numbers - 1
# 1 - 2
# 2 - 3
# 3 - 4
# float - 5
# 225.6 - 6
# True - 7
# False - 8

print(random[:])
print(random[5:8])
print(random[:5]) # 5 excluding 
print(random[5:]) # 5 including

In [ ]:
random = ["names","numbers",1,2,3,"float",225.6,True,False]
# names - 0
# numbers - 1
# 1 - 2
# 2 - 3
# 3 - 4
# float - 5
# 225.6 - 6
# True - 7
# False - 8
print(random[:8])
print(random[:8:1])
print(random[:8:2])

In [ ]:
names = ["batman","superman","greenlantern","flash","robinhood"]
a = "parrot"
print(a[1:4])
print(names[1:4])
print(names[0:5])
print(names[0:5:1])
print(names[0:5:2])

In [ ]:
#example for negative indexing

In [ ]:
##example for slicing with negative indices

In [ ]:
# example for 2-d slicing

<font color=red>**Question 6**</font><br>
Predict the output of the following code snippet:
```
random_list = ['Python',100,10.5,200,'Java',[1,2,3]]
print("i. ", random_list[1:])
print("ii. ", random_list[4:-1])
print("iii. ", random_list[0:6:2])
print("iv. ", random_list[4:5])
print("v. ", random_list[-2:-1])
print("vi. ", random_list[::-1])

```

## Methods in List

### extend()

In [ ]:
num_1 = [1,2,3]
num_2 = [4,5,6]
num_5 = num_1 + num_2
print("num_5",num_5)
print("num_1",num_1)
print("num_2",num_2)

Syntax
```
list_to_be_changed.extend(list_to_be_added)
```

In [ ]:
num_1 = [1,2,3]
num_2 = [4,5,6]


num_2.extend(num_1)
print(num_2)
print(num_1)

In [ ]:
# Extend
num_1 = [1,2,3,4,5]
num_2 = [6,7,8]
print(num_1+num_2)
# list_1.extend(list_2) ------ syntax for extend
print("num_1 list before use of extend:",num_1)
num_1.extend(num_2)
print("num_1 list after use of extend:",num_1)

In [ ]:
num_1 = [1,2,3,4,5]
num_2 = [6,7,8]
print(num_1+num_2)
print(num_1)
print(num_2)

### Index()

**Getting the index using index() method:**

We know the value of a element in the list but do not know the index of that element then we can use this method
- This gets the index of an element of the list
- **Syntax:**
```
index_value = name_of_list.index(element)
```

In [ ]:
# finding the index :: Syntax --- list.index(value)
num = [1,2,3,4]
index_num = num.index(1)
print(index_num)

In [ ]:
# remove - gayathri from the list
name = ['rekha', 'mishal', 'Anjana_K',"athira"]
print(name)
print("Length:",len(name))
print("-------------")
index_number = name.index("athira")
# print(index_number)
name.pop(index_number)
print("-----------")
print(name)
print("length:",len(name))

In [ ]:
# remove - gayathri from the list
# get the name to remove from user

In [ ]:
names = ["Akshaya","Ajanya","Shahan","Hisham","Akarsh","Adarsh","Arjun","Amrutha","Arya VK","Arya K"]
print(names)
a = names.pop(2)
print(a)
print(names)

In [ ]:
names = ["Akshaya","Ajanya","Shahan","Hisham","Akarsh","Adarsh","Arjun"]
print(names)
del names[1]
print(names)
del names[4]
print(names)

In [ ]:
names = ["Akshaya","Ajanya","Shahan","Hisham","Akarsh","Adarsh","Arjun","Amrutha","Arya VK","Arya K"]
names.remove("Ajanya")
print(names)
a = names.pop() # no_index_given , Delets last element
print(a) # removed element
print(names)

### Methods for deleting elements

#### 1. pop()
- We should know the index of the value to be deleted
- INDEX SHOULD BE KNOWN
- Advantage :: Returns the deleted value

In [ ]:
# pop
name = ["mango","apple","banana"]
a = name.pop(2)
print(a)
print(name)

In [ ]:
# Problem - We have to remove gayathri from this list
name = ['rekha', 'mishal', 'Anjana_K', 'athira', 'ifna', 'abhinav', 'niharika', 'aiswarya', 'Muhammed Mishal', 'gayathri']

name.pop(1)

In [ ]:
upgraded=[]
name = ["mehna","sahad","deviga","rohan","archana","amelia","amisha","tahseen","ganga"]
a = name.pop(0) # deleted
upgraded.append(a) # added to update list
name.append("bashid")
upgraded.append(name.pop(3))
print(name)
print(upgraded)

#### 2. del
- No return Value
- NEED THE INDEX

`del name_of_list[index]`   



Can be used for:
- deleting single element
- deleting consecutive elements
- deleting by step
- deleting the list

In [ ]:
# del
name = ["mango","apple","banana"]
del name[1]
print(name)

In [ ]:
name = ["mehna","sahad","deviga","rohan","archana","amelia","amisha","tahseen","ganga","bashid","goutham","hridhika"]
del name[11]
print(name)

In [ ]:
name = ["mehna","sahad","deviga","rohan","archana","amelia","amisha","tahseen","ganga","bashid","goutham","hridhika"]
last_index = len(name)-1
del name[last_index]
print(name)

In [ ]:
name = ["mehna","sahad","deviga","rohan","archana","amelia","amisha","tahseen","ganga","bashid","goutham","hridhika"]
del name[6]
print(name)

In [ ]:
name = ["mehna","sahad","deviga","rohan","archana","amelia","amisha","tahseen","ganga","bashid","goutham","hridhika"]
del name[6:10]
print(name)

['mehna', 'sahad', 'deviga', 'rohan', 'archana', 'amelia', 'goutham', 'hridhika']

In [ ]:
del name[]

#### 3. remove()
- Value should be known
- INDEX NOT NEEDED

`list_name.remove(value)`

In [ ]:
name = ['rekha', 'mishal', 'Anjana_K', 'athira', 'ifna', 'abhinav', 'niharika', 'aiswarya', 'Muhammed Mishal', 'gayathri']
name.remove("rekha")
print(name)

In [ ]:
name = ["mehna","sahad","deviga","rohan","archana","amelia","amisha","tahseen","ganga","bashid","goutham","hridhika"]
name.remove("amisha")
print(name)

<font color = red>**Question 7**</font>

Note :: Do using pop,del and remove

name = ["ramu","sonu","gholu","kalia"]

- Take a name as input from user 
    - "Enter the value to be deleted"
- delete the name from the list
- Print the updated list

In [ ]:
# question 7

### Lists and functions

In [ ]:
num = [1,2,3,4,5,6,7,8,9,10]
max(num)

10

In [ ]:
num = [1,2,3,4,5,6,7,8,9,10]
min(num)

1

In [ ]:
num = [1,2,3,4,5,6,7,8,9,10]
sum(num)

55

In [ ]:
num = [1,2,3,4,5,6,7,8,9,10]
len(num)

In [ ]:
num = [1,2,3,4,5,6,7,8,9,10]
# averge = sum / total elements
avg = sum(num)/len(num)
print(avg)

<font color = red>**Question 8**</font>
- Take the names of students :: 4 students from user
- Take their score out of 50 
- print the student who scored highest mark
- print the student who scored lowest mark
- print the class average
----
OUTPUT:
```
Enter name: Amal
Enter mark: 40
Enter name: Nikhila
Enter mark: 41
Enter name: Manu
Enter mark: 34
Enter name: Suhail
Enter mark: 49
------------------
Highest: Suhail 49
Lowest: Manu 34
Class Average: 41.0
```


-----

## List and Strings

Converting a string to lists

In [ ]:
name = "my name is bashid"
new_list = list(name)
print(new_list)
print(new_list[3])

['m', 'y', ' ', 'n', 'a', 'm', 'e', ' ', 'i', 's', ' ', 'b', 'a', 's', 'h', 'i', 'd']
n

### Split
- Has a return value

`str_to_be_splitted.split()`

In [ ]:
name = "my name is bashid"
name.split()

['my', 'name', 'is', 'bashid']

In [ ]:
name = "my name is bashid"
new_list = name.split()
for line in new_list:
    print(line)

 `Split(delimiter)`

In [ ]:
name = "mehna,sahad,deviga,rohan,archana,amelia,amisha,tahseen,ganga,bashid,goutham,hridhika"
new_list = name.split(",")
print(new_list)

In [ ]:
name = "mehna#sahad#deviga#rohan#archana#amelia#amisha#tahseen#ganga#bashid#goutham#hridhika"
new_list = name.split("#")
print(new_list)

Question
- Take input names from user until the user enters done
- Store the data to a list
- Print the list

In [ ]:
new_list = list()
while True:
    name = input("Enter name:")
    if name == "done":
        break
    new_list.append(name)
print(new_list)

<font color = red>**Question 9**</font>
- Take input from user as student's names seperated by commas(,) in single line
- Store the names into a list
- Print the list

In [ ]:
#code for question9

-----

### Changeable

**Have you noticed????**    
What is the difference between functions operating over list and methods operating over list?

- `len()`,`max()`,`min()`,`sum()` are some examples for functions in list.

- `append()`, `insert()`, `extend()`, `remove()` etc are some examples for methods in list.

In [ ]:
my_list = [1,2,3,4,5,6]
my_list[1] = 8
print(my_list)

In [ ]:
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "mango"]
thislist[1:3] = ["blackcurrant", "watermelon"]
print(thislist)

['apple', 'blackcurrant', 'watermelon', 'orange', 'kiwi', 'mango']

In [ ]:
thislist = ["apple", "banana", "cherry"]
thislist.insert(2,"watermelon")
print(thislist)

In [ ]:
thislist = ["apple", "banana", "cherry"]
thistuple = ("kiwi", "orange")
thislist.extend(thistuple)
print(thislist)

In [ ]:
thislist = ["apple", "banana", "cherry"]
del thislist

In [ ]:
thislist = ["apple", "banana", "cherry"]
thislist.clear()
print(thislist)

### Clearing a list

In [ ]:
name = ["bashid","afsal","numan"]
name.clear()
print(name)

### Deleting a List

In [ ]:
name = ["bashid","afsal","numan"]
del name[1:2]
print(name)

['bashid', 'numan']

In [ ]:
name = ["bashid","afsal","numan"]
del name[:]
print(name)

[]

In [ ]:
name = ["bashid","afsal","numan"]
name *= 0
print(name)

[]

In [ ]:
del name
print(name)

NameError: name 'name' is not defined

### Aliasing

In [ ]:
a = [1,2,3]
b=a
a[1]=5
print(a)
print(b)

[1, 5, 3]
[1, 5, 3]

## cloaning

In [ ]:
a = [1,2,3]
b=a[:]
a[1]=5
print(a)
print(b)

[1, 5, 3]
[1, 2, 3]

In [ ]:
a = [1,2,3]
b= []
b=a.copy()
print(b)

[1, 2, 3]

# Sorted VS Sort

In [ ]:
a = [55,44,67,98,10]
a.sort()
print(a)

[10, 44, 55, 67, 98]

In [ ]:
a = [55,44,67,98,10]
b = sorted(a)
print(b)

[10, 44, 55, 67, 98]

<font color =red>**Question 10**</font>
- Create a function clone
- It returns a new list with the same elements as the list passed to the function
Example:
```
b = [1,2,3]
a = clone(b)
print(a) # this should print a list identical to b
```

In [ ]:
#code question 10

-----
-----

# Activities

<font color =red>**Activity 1**</font>
```
- Take 5 integer inputs from user and store them in a list.
- print the list
- Update each element by it's cube
- print the altered list
```
----
OUTPUT:
```
Enter a number: 5
Enter a number: 6
Enter a number: 10
Enter a number: 8
Enter a number: 11
[5,6,10,8,11]
[125,216,1000,512,1331]
```

<font color =red>**Activity 2**</font>
```
Take 10 integer inputs from user and store them in a list. Again ask user to give a number. Now, tell user whether that number is present in list or not.
```

<font color =red>**Activity 3**</font>
```
Take 10 integer inputs from user and store them in a list.
Now, copy all the elements in another list but in reverse order.
And print the copy list.
```

<font color =red>**Activity 4**</font>
```
- Take name and mark(out of 100) of five students from user.
- Save the details into student_list and mark_list
- Print the student names and their respective marks in the descending order
```

<font color =red>**Activity 5**</font>
Consider the given list and perform the following tasks:
`lis = ['ABCD','QWERTY','india',True,'1010','#',True,False]`
1. Count number of True present in the list
2. Change the first letter of 'india' into Capital letter.
3. Find the index of '#'
4. Print list in reverse order
5. Create a new_list containing all the string types
6. Delete element '#'
7. Print the alternative elements of the list

<font color =red>**Activity 6**</font>
- Take 20 integers as input from user in single line separated by ':' and find the following:
- number of positive numbers
- number of negative numbers
- number of odd numbers
- number of even numbers
- number of 0s.

---