# Index

- **For Loop**   
    - **Traversal Through List**
    - **Break and Continue**
    - **Range function**
    - **Nested for loop**
    - **Enumerate**
    - **Else with for loop**
    
    
- **Activities**

In [ ]:
# printing list elemenets as list
names = ["mishal","thulasi","ifna","anjana","rekha","arsha","gayathri"]

In [ ]:
# printing list elemenets as list one-by-one using each index
names = ["mishal","thulasi","ifna","anjana","rekha","arsha","gayathri"]

In [ ]:
# printing list elemenets usinh while loop
names = ["mishal","thulasi","ifna","anjana","rekha","arsha","gayathri"]

# For Loop

- It can iterate over the items of any sequence such as list, string, tuple, dictionary etc
- It has three parts:
    - iterating variable
    - sequence (list, string, tuple, dictionary etc)
    - body of the loop (set of statments need to be executed repeatedly)

- **Syntax:**
```
for iter_variable in sequence:
            statements
```

## Traversal Through List

In [ ]:
# using while loop

In [ ]:
# printing list elemenets using while loop
names = ["mishal","thulasi","ifna","anjana","rekha","arsha","gayathri"]

In [ ]:
# printing list elemenets using while loop
numbers = [1,23,5,6]

In [ ]:
# sum of all numbers in a list

numbers = [1,23,5,6]

Sum=0
for num in numbers:
    Sum=Sum+num # value of sum is updated after each iteration
#     print(Sum)
print(Sum)

35

In [ ]:
# Searching for a particular name in the names list:
names = ["mishal","thulasi","ifna","anjana","rekha","arsha","gayathri"]

<font color=red>**Question 1**</font><br>
Check if the numbers inside the list is even or odd!
 - If even print number is even 
- If odd print odd

`List = [22,35,45,88,22,44,96]`
```
Output:
num = 22,Even
num = 35,Odd
...num = 96,Even
```

<font color=red>**Question 2**</font><br>
- check how many "a" are there in the loop

`cha = ["a","b","a","c","a","d","f"]`
```
Output
Number of a in list = 3
```

#### Iterations in for

In [ ]:
# Example
# we have 3 elements so loop runs 3 times
fruits = ["apple","mango","avocado"]
count = 1
for a in fruits:
    print("Loop:",count)
    count=count+1
    print("value of a:",a)

Loop: 1
value of a: apple
Loop: 2
value of a: mango
Loop: 3
value of a: avocado

In [ ]:
# Example
# we have 6 elements so loop runs 6 times
fruits = ["apple","mango","avocado","papaya","banana","Guava"]
count = 1
for a in fruits:
    print("Loop:",count)
    count=count+1
    print("value of a:",a)

Loop: 1
value of a: apple
Loop: 2
value of a: mango
Loop: 3
value of a: avocado
Loop: 4
value of a: papaya
Loop: 5
value of a: banana
Loop: 6
value of a: Guava

In [ ]:
# Question 2 : numbers = [22,55,44,66,88,77]
# print the sum of the numbers in the list numbers using for loop
# hint 
# 22 + 55 = 77
# 77 + 44 = 121
# 121 + 66 = 187
# 187 + 88 = 275
# 275 + 77 = 352

sum_a = 0
count = 0
numbers = [22,55,44,66,88,77] # sum = 22+55+44+66+88+77 = 352
for a in numbers:
    count =count +1
    print("value of a",a)
    print("loop =",count)
    sum_a = sum_a + a
    print("sum=",sum_a)
print("Final ",sum_a)

value of a 22
loop = 1
sum= 22
value of a 55
loop = 2
sum= 77
value of a 44
loop = 3
sum= 121
value of a 66
loop = 4
sum= 187
value of a 88
loop = 5
sum= 275
value of a 77
loop = 6
sum= 352
Final  352

```
sum_a = 0
numbers = [22,55,44,66,88,77]
for a in numbers:
    sum_a = sum_a + a
print(sum_a)
```

loop|value of a|sum_a|
---|---|---|
0|0|0
1|22|22
2|55|77
3|44|121
4|66|187

**Note:** 
```
    In general while we traversing a sequence(list) using for loop, the loop will execute `n` number of iterations;
    Where `n` is the length of the sequence(list)
```

<font color=red>**Question 3**</font><br>
Let `prime_nums` be a list containing all the prime numbers between 1 and 25. And you traversed the `prime_nums` using for loop. <br>
1. What will be the number of iteration occured?
2. How many times the loop visited the each element in `prime_nums` ?

```
Option A : 1. 10    2. 10
Option B : 1. 10    2. 9
Option C : 1. 9     2. 1
Option D : 1. 9     2. 9
Option E : 1. 10    2. 0
```

In [ ]:
# Code for question 3

#### Altering the list elements while traversing

In [ ]:
name = [1,2,2,3,4,55,"a","avh",22.2,55.6]
print(name)
name.append(2)
print(name)

[1, 2, 2, 3, 4, 55, 'a', 'avh', 22.2, 55.6]
[1, 2, 2, 3, 4, 55, 'a', 'avh', 22.2, 55.6, 2]

<font color=red>**Question 4**</font><br>
```
Let numbers = [1,2,3,4,'yes']
print all the elements inside the list numbers and when yes is printed, print ':string' along with it
```

In [ ]:
#code for question4

<font color=red>**Question 5**</font><br>
`List = [1,2,22.4,"aks",[1,2,3]]`

Write a program to print the element of the list along with the type of the element

In [ ]:
#code for question 5

Get different names from user as input
- store them to a list
- print the list
- when user types stop - the program should stop
```
Enter name :arjun
Enter name : arun
Enter name : done
names = ["arjun","arun"]
```

In [ ]:
list_new = [] # new empty list
while True: # making a infinite loop
    name = input("Enter name:") # getting input from user
    if name == "done": # checking if name entered is "done"
        break #stop the loop
    list_new.append(name)

print(list_new)

Enter name:a
Enter name:a
Enter name:s
Enter name:f
Enter name:v
Enter name:dd
Enter name:ffwewe
Enter name:done
['a', 'a', 's', 'f', 'v', 'dd', 'ffwewe']

In [ ]:
a= 0
for names in ["arj","aru","aks","aka"]:
    print(names)
# Loop 1 :

## Break

#### Print the elements till 35(excluded) , in the given  list below
```
num = [1,22,55,85,66,35,45,85,55]
```

In [2]:
num = [1,22,55,85,66,35,45,85,55]
for n in num:
    if n==35:
        break
    print(n)

1
22
55
85
66

In [ ]:
num = [1,22,55,85,66,35,45,85,55]
for n in num:
    if n==num[5]:
        break
    print(n)

1
22
55
85
66

In [ ]:
# Use Break Statement
# Print the elements till 35(exclueded) , in the given below list
num = [1,22,55,85,66,35,45,85,55]
for number in num:
    print(number)
    if(number==66):
        break

## Continue

#### Print all elements except 35
```
num = [1,22,55,85,66,35,45,85,55]
```

In [ ]:
#code here without continue

In [ ]:
#code here using continue statements

In [ ]:
# Print all the elements, skip 66
# without continue

num = [1,22,55,85,66,35,45,85,55]
for a in num:
    if a!=66:
        print(a)

1
22
55
85
35
45
85
55

In [ ]:
# Print all the elements, skip 66
# using continue
num = [1,22,55,85,66,35,45,85,55]
for a in num:
    if a==66:
      continue
    else:  
        print(a)

In [ ]:
# QUESTION
# Print all the elements, and if 66 - print SixtySix
num = [1,22,55,85,66,35,45,85,55]

## Nested For loops

- Loop inside another loop

In [ ]:
# for loop inside a for loop
adj = ["red", "big", "tasty"]
fruits = ["apple", "banana", "cherry"]

for x in adj:
    for y in fruits:
        print(x, y)

red apple
red banana
red cherry
big apple
big banana
big cherry
tasty apple
tasty banana
tasty cherry

<font color=red>**Question 5**</font><br>
``` 
Arun created a python list containing some fruits as:
fruits = ['apple','pear','tomato','mango','banana']
Later he want to change the  'tomato' into 'grapes' inside a for loop.
But it is having some error ? Could you find out and fix it?
```
Code Snippet:<br>
```
fruits = ['apple','pear','tomato','mango','banana']

for item in fruits:
    if item == 'tomato':
        item = 'grapes'

print(fruits)
```

## Range

Range with a single argument <br>
`range(argument)`
- here range will print numbers from 0 till the value passed in the argument, in incrementation of 1

In [ ]:
# using only single argument in range
# using range with For Loop
for num in range(5,11):
    print(num)

5
6
7
8
9
10

In [ ]:
# using only single argument in range
# using range with For Loop
for num in range(0,11,2):
    print(num)

0
2
4
6
8
10

```
for num in range(10):
    print(num)
```
Lets see how this code works
- Num will have values from 0 till 9(as range(10))
- after each iteration the value of num will be incremented with 1
    - loop 1 :: num =0
    - loop 2 :: num =1
    ...... and so on 
    - loop 10 :: num =9
- Hence the above code will print numbers from 0 till 9

for a in range(5):
    for b in range(a):
        print(b)

In [ ]:
for a in range(5):
    for b in range(a):
        print(b,end="")

0010120123

In [ ]:
for a in range(5):
    print(a)

0
1
2
3
4

In [ ]:
for a in range(1,6):
    print(a,end="")

12345

In [ ]:
for a in range (1,6):
    for b in range(1,a+1):
        print(b,end="")

112123123412345

In [ ]:
for a in range (1,6):
    for b in range(1,a+1):
        print(b,end="")

In [ ]:
for a in range (1,6):
    for b in range(1,a+1):
        print(b,end="")
    print()

1
12
123
1234
12345

In [ ]:
for a in range (1,6):
    for b in range(5,a+1):
        print(b,end="")
    print()

In [ ]:
for a in range(5):
    print(a,"")

0
1
2
3
4

<font color=red><strong>Question 6:</strong></font>
Write a program using for loops to print the following pattern <br>
```
Print this pattern
1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5
```

In [ ]:
# NOT recommended Method
print("1")
print("1 2")
print("1 2 3")
print("1 2 3 4")
print("1 2 3 4 5")

1
1 2
1 2 3
1 2 3 4
1 2 3 4 5

# Enumerate

- enumerate() method adds a counter to an iterable and returns it in a form of enumerating object.


**Syntax:**
`enumerate(iterable, start=0)` <br>
```
    Where iterable is any sequence that can be iterate
          start is the index in which couter need to be started
```

In [ ]:
for i,j in enumerate([1,2,3]):
    print(i,j)

0 1
1 2
2 3

In [ ]:
numbers = [2,3,5,7,11,13,17,19]
for item in enumerate(numbers):
    print(item)

(0, 2)
(1, 3)
(2, 5)
(3, 7)
(4, 11)
(5, 13)
(6, 17)
(7, 19)

In [ ]:
numbers = [2,3,5,7,11,13,17,19]
for index,item in enumerate(numbers):
    print(index,item)

0 2
1 3
2 5
3 7
4 11
5 13
6 17
7 19

In [ ]:
numbers = [2,3,5,7,11,13,17,19]
for index,item in enumerate(numbers,10):
    print(index,item)

10 2
11 3
12 5
13 7
14 11
15 13
16 17
17 19

## Else with Loop

- In python, an else statement can be associated with a loop statement


- It is an optional feature


- If the else statement is used with a for loop, the else statement is executed when the loop has exhausted iterating the list.


- If the else statement is used with a while loop, the else statement is executed when the condition becomes `False`.

In [ ]:
# Else in for loop
names = ['Arun','AnitHa','Bincy','Fayis','Nikhil']

for name in names:
    print(name)
else:
    print('Name list had ended!')

Arun
AnitHa
Bincy
Fayis
Nikhil
Name list had ended!

In [ ]:
n = 10

while(n>=0):
    print(n)
    n = n-1
else:
   print("Reached negative numbers")

10
9
8
7
6
5
4
3
2
1
0
Reached negative numbers

----

# Activities

<font color=red><strong>Activity 1</strong></font><br>
Write a program to display the multiplication table of 24 using for loop upto 10 rows.

<font color=red><strong>Activity 2</strong></font><br>
```
Accept 5 names from user and store them in a list called names.
Then print each name along with the legth of the name
```
-----

OUTPUT:
```
Enter name: Akhil
Enter name: Neerav
Enter name: Ann
Enter name: Sunil
Enter name: Peter John

Akhil : 5
Neerav : 6
Ann : 3
Sunil : 5
Peter John : 10
```

<font color=red><strong>Activity 3</strong></font><br>
```
Take integer inputs from user until he/she presses q ( Ask to press q to quit after every integer input ).
Then print the list, sum and average of all numbers.
```
-----
OUTPUT:
```
Enter an integer: 5
Press q to quit and any key for continue: a
Enter an integer: 4
Press q to quit and any key for continue: f
Enter an integer: 7
Press q to quit and any key for continue: 3
Enter an integer: 8
Press q to quit and any key for continue: q

List = [5,4,7,8]
Sum = 24
Average = 6.0
```

<font color=red><strong>Activity 4</strong></font><br>
```
Write a program to find all the factors of user entered number in asceding order
```
-------
OUTPUT:    
- Case1
```
Enter a number: 12
Factors of 12: 1  2  3  4  6  12
```
- Case2
```
Enter a number: 17
Factors of 17: 1  17
```

<font color=red><strong>Activity 5</strong></font><br>
```
Consider the following list:
    city = ['Kolkata','Kochi','Thiruvananthapuram','Chennai','Mumbai','Pune']
    - Print the city which has lengthiest and shortest name in the list
    - Change the name of 'Kochi' into 'Cochin'
    - Count the number of times, letter 'a' present in the city 'Thiruvananthapuram'.
    - Count the number of times, letter 'i' present in the entire list.
```

<font color=red><strong>Activity 6</strong></font><br>
```
all_list = ['qwerty',121,89,'A','Hello',11.11,'Welcome',-12,0.50]
From the above list containing ints, strings and floats, make three lists to store them separately.
```
OUTPUT:
```
int_list: [121,89,-12]
str_list: ['qwerty','A','Hello','Welcome']
float_list: [11.11,0.5]
```

<font color=red><strong>Activity 7</strong></font><br>
Print the following patterns using loop :

1.
```
1010101
 10101 
  101  
   1
```

2. 
```
     *
    ***
   *****
  *******
```


3. 
```
      1
     121
    12321
   1234321  
```

----